name: Auto Generate Film Posts

on:
  schedule:
    - cron: "0 */6 * * *"   # jalan tiap 6 jam
  workflow_dispatch:        # bisa run manual dari tab Actions
  push:
    paths:
      - script.py
      - .github/workflows/auto-generate.yml

permissions:
  contents: write           # izinkan commit ke repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install feedparser

      - name: Run generator
        run: python script.py

      - name: Commit & push generated posts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add posts/
          git commit -m "Auto-generate posts [skip ci]" || echo "No changes"
          git push
